### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by dvdobrovolskiy** [iolevel/wpdotnet-sdk#14]
Hi

Getting this url (customizing theme)
http://vr.dobrovolskiy.com/wp-admin/customize.php

brings 500 error

`info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://vr.dobrovolskiy.com/wp-admin/customize.php
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLJ0G5E7P9QV", Request id "0HLJ0G5E7P9QV:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Pchp.Library.PCRE.Match(Context ctx, String pattern, String subject, PhpArray& matches, Int32 flags, Int64 offset, Boolean matchAll)
   at <Root>wp-includes.functions_php.validate_file(Context <ctx>, PhpValue file, PhpValue allowed_files)
   at WP_Customize_Manager.__construct(PhpValue args)
   at <Root>wp-includes.theme_php._wp_customize_include(Context <ctx>)
   at _wp_customize_include#1(Closure , Context , PhpValue[] )
   at WP_Hook.apply_filters(PhpValue value, PhpValue args)
   at WP_Hook.do_action(PhpValue args)
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpArray )
   at <Root>wp-includes.plugin_php.do_action(Context <ctx>, PhpValue tag, PhpValue[] <arguments>)
   at <Root>.wp-settings_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>.wp-config_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>.wp-config_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>.wp-load_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>.wp-load_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>wp-admin.admin_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>wp-admin.admin_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>wp-admin.customize_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>wp-admin.customize_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.<>c__DisplayClass7_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
`
Using fresh peachpie-wordpress project 

<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.5" />
    <PackageReference Include="PeachPied.WordPress.AspNetCore" Version="1.0.0-alpha3" />
    <PackageReference Include="Peachpie.AspNetCore.Mvc" Version="0.9.25" />

**Update**
quite a lot of such and error
here at image crop
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 59.0472ms 200 application/json; charset=UTF-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://vr.dobrovolskiy.com/wp-admin/admin-ajax.php application/x-www-form-urlencoded; charset=UTF-8 231
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLJ0G5E7P9VU", Request id "0HLJ0G5E7P9VU:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Pchp.Library.PCRE.Match(Context ctx, String pattern, String subject, PhpArray& matches, Int32 flags, Int64 offset, Boolean matchAll)
   at <Root>wp-includes.functions_php.validate_file(Context <ctx>, PhpValue file, PhpValue allowed_files)
   at WP_Customize_Manager.__construct(PhpValue args)
   at <Root>wp-includes.theme_php._wp_customize_include(Context <ctx>)
   at _wp_customize_include#1(Closure , Context , PhpValue[] )
   at WP_Hook.apply_filters(PhpValue value, PhpValue args)
   at WP_Hook.do_action(PhpValue args)
   at CallSite.Target(Closure , CallSite , PhpValue , Context , PhpArray )
   at <Root>wp-includes.plugin_php.do_action(Context <ctx>, PhpValue tag, PhpValue[] <arguments>)
   at <Root>.wp-settings_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>.wp-config_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>.wp-config_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>.wp-load_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>.wp-load_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>wp-admin.admin-ajax_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>wp-admin.admin-ajax_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.<>c__DisplayClass7_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]

**Comment by jakubmisek** [comment]
Hi, confirmed.

**Comment by jakubmisek** [comment]
The issue with `PCRE.Match` has just been fixed in the latest peachpie and the latest `wpdotnet-sdk`. https://github.com/iolevel/peachpie-wordpress has been updated as well.
