### ISSUE TITLE
System.InvalidCastException when hooking wp_get_attachment_image_attributes filter

### ISSUE THREAD

**Issue by diddledan** [iolevel/wpdotnet-sdk#43]
**Describe the bug**
The site will error when a function has been hooked onto the WordPress core filter `wp_get_attachment_image_attributes` with a stacktrace.

**To Reproduce**
This is a bit involved, but is the simplest I managed to make it:

1. Clone https://github.com/diddledan/attachment-filter-fail
    * The code that triggers the error is at https://github.com/diddledan/attachment-filter-fail/blob/master/testtheme/wp-content/themes/theme/functions.php
1. Compile and run the site
1. Go through the WordPress installation routine
1. Login to the admin and navigate to appearance->themes and choose `testtheme`
1. Navigate to appearance->customize->site identity and upload a new logo image (I used a png image in my test)
1. Once the image is uploaded the site will be broken whenever it tries to display that logo on the frontend. The customize screen should also fail to update once you click the upload/crop button.

**Expected behavior**
The code should successfully return from calling into the filter `wp_get_attachment_image_attributes` without triggering an invalid cast exception.

**System information:**
 - OS: [e.g. iOS] Ubuntu Linux 19.04
 - Version [e.g. 1.04] PeachPie 0.9.44; WPDotNet 1.0.0-beta8; dotnet sdk 2.2.401

**Stack trace:**
```plain
System.InvalidCastException: Specified cast is not valid.
   at Pchp.Core.PhpValue.TypeTable.GetArray(PhpValue& me)
   at <Root>wp-includes.media_php.wp_get_attachment_image(Context <ctx>, PhpValue attachment_id, PhpValue size, PhpValue icon, PhpValue attr)
   at <Root>wp-includes.general-template_php.get_custom_logo(Context <ctx>, PhpValue blog_id)
   at <Root>wp-includes.general-template_php.the_custom_logo(Context <ctx>, PhpValue blog_id)
   at <Root>wp-content/themes/twentynineteen/template-parts/header.site-branding_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>wp-content/themes/twentynineteen/template-parts/header.site-branding_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>wp-includes.template_php.load_template(Context <ctx>, PhpValue _template_file, PhpValue require_once)
   at <Root>wp-includes.template_php.locate_template(Context <ctx>, PhpValue template_names, PhpValue load, PhpValue require_once)
   at <Root>wp-includes.general-template_php.get_template_part(Context <ctx>, PhpValue slug, PhpValue name)
   at <Root>wp-content/themes/twentynineteen.header_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>wp-content/themes/twentynineteen.header_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>wp-includes.template_php.load_template(Context <ctx>, PhpValue _template_file, PhpValue require_once)
   at <Root>wp-includes.template_php.locate_template(Context <ctx>, PhpValue template_names, PhpValue load, PhpValue require_once)
   at <Root>wp-includes.general-template_php.get_header(Context <ctx>, PhpValue name)
   at <Root>wp-content/themes/twentynineteen.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>wp-content/themes/twentynineteen.index_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>wp-includes.template-loader_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>.wp-blog-header_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>.wp-blog-header_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Pchp.Core.Context.Include(String cd, String path, PhpArray locals, Object this, RuntimeTypeHandle self, Boolean once, Boolean throwOnError)
   at <Root>.index_php.<Main>(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at <Root>.index_php.<Main>`0(Context <ctx>, PhpArray <locals>, Object this, RuntimeTypeHandle <self>)
   at Pchp.Core.Context.ScriptInfo.Evaluate(Context ctx, PhpArray locals, Object this, RuntimeTypeHandle self)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo script)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.<>c__DisplayClass7_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at PeachPied.WordPress.AspNetCore.Internal.WpResponseCacheMiddleware.Invoke(HttpContext context)
   at PeachPied.WordPress.AspNetCore.Internal.DiagnosticExtensions.Middleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by jakubmisek** [comment]
seems that causes `$attr` to not be an array after the following line of code:
https://github.com/iolevel/wpdotnet-sdk/blob/caf68cd0c3837c682145fffb27a59c4089a5bc88/wordpress/wp-includes/media.php#L920

Can you please quickly check what is the type of `$attr` after this line? We'll take a look soon.

Thank you!

**Comment by jakubmisek** [comment]
with the upcoming update of PeachPie runtime this should behave like in PHP
- the provided user callback was invalid, although the value of `$arg` was not `array` but `boolean`
- runtime raises `TypeError` exception now properly
