### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by hez2010** [iolevel/wpdotnet-sdk#85]
**Describe the bug**
Sometimes it runs into System.AccessViolationException.

**To Reproduce**
I don't know how to reproduce.
My wordpress server always crashes after a period of time since 5.5.1-preview1.

**System information:**
 - OS: Ubuntu 20.04
 - .NET: 5.0 preview 8

**Stack trace:**
```none
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr, Void (IntPtr, IntPtr, IntPtr*), IntPtr)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Pchp.Core.Context, System.String, Pchp.Core.PhpAlias)
   at <Root>wp-includes.formatting_php.wp_parse_str(Pchp.Core.Context, Pchp.Core.PhpValue, Pchp.Core.PhpAlias)
   at <Root>wp-includes.functions_php.add_query_arg(Pchp.Core.Context, Pchp.Core.PhpValue[])
   at <Root>wp-includes.script-loader_php.wp_get_script_polyfill(Pchp.Core.Context, Pchp.Core.PhpValue, Pchp.Core.PhpValue)
   at <Root>wp-includes.script-loader_php.wp_default_packages_vendor(Pchp.Core.Context, Pchp.Core.PhpValue)
   at <Root>wp-includes.script-loader_php.wp_default_packages(Pchp.Core.Context, Pchp.Core.PhpValue)
   at DynamicClass.wp_default_packages#1(System.Runtime.CompilerServices.Closure, Pchp.Core.Context, Pchp.Core.PhpValue[])
   at WP_Hook.apply_filters(Pchp.Core.PhpValue, Pchp.Core.PhpValue)
   at WP_Hook.do_action(Pchp.Core.PhpValue)
   at <Root>wp-includes.plugin_php.do_action_ref_array(Pchp.Core.Context, Pchp.Core.PhpValue, Pchp.Core.PhpValue, Pchp.Core.PhpValue[])
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr, Void (IntPtr, IntPtr, IntPtr*), IntPtr)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Pchp.Core.Context, System.String, Pchp.Core.PhpArray)
   at WP_Scripts.init()
   at WP_Scripts.__construct()
   at <Root>wp-includes.functions_wp-scripts_php.wp_scripts(Pchp.Core.Context)
   at <Root>wp-includes.functions_wp-scripts_php.wp_add_inline_script(Pchp.Core.Context, Pchp.Core.PhpValue, Pchp.Core.PhpValue, Pchp.Core.PhpValue)
   at WP_Widget_Text._register_one(Pchp.Core.PhpValue)
   at WP_Widget._register()
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Pchp.Core.PhpValue, Pchp.Core.Context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[[Pchp.Core.PhpValue, Peachpie.Runtime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5b4bee2bf1f98593],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Runtime.CompilerServices.CallSite, Pchp.Core.PhpValue, System.__Canon)
   at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Pchp.Core.PhpValue, Pchp.Core.Context)
   at WP_Widget_Factory._register_widgets()
   at WP_Hook.apply_filters(Pchp.Core.PhpValue, Pchp.Core.PhpValue)
   at WP_Hook.do_action(Pchp.Core.PhpValue)
   at <Root>wp-includes.plugin_php.do_action(Pchp.Core.Context, Pchp.Core.PhpValue, Pchp.Core.PhpValue[])
   at <Root>wp-includes.widgets_php.wp_widgets_init(Pchp.Core.Context)
   at DynamicClass.wp_widgets_init#1(System.Runtime.CompilerServices.Closure, Pchp.Core.Context, Pchp.Core.PhpValue[])
   at WP_Hook.apply_filters(Pchp.Core.PhpValue, Pchp.Core.PhpValue)
   at WP_Hook.do_action(Pchp.Core.PhpValue)
   at <Root>wp-includes.plugin_php.do_action(Pchp.Core.Context, Pchp.Core.PhpValue, Pchp.Core.PhpValue[])
   at <Root>.wp-settings_php.<Main>(Pchp.Core.Context, Pchp.Core.PhpArray, System.Object, System.RuntimeTypeHandle)
   at Pchp.Core.Context.Include(System.String, System.String, Pchp.Core.PhpArray, System.Object, System.RuntimeTypeHandle, Boolean, Boolean)
   at <Root>.wp-config_php.<Main>(Pchp.Core.Context, Pchp.Core.PhpArray, System.Object, System.RuntimeTypeHandle)
   at <Root>.wp-config_php.<Main>`0(Pchp.Core.Context, Pchp.Core.PhpArray, System.Object, System.RuntimeTypeHandle)
   at Pchp.Core.Context.Include(System.String, System.String, Pchp.Core.PhpArray, System.Object, System.RuntimeTypeHandle, Boolean, Boolean)
   at <Root>.wp-load_php.<Main>(Pchp.Core.Context, Pchp.Core.PhpArray, System.Object, System.RuntimeTypeHandle)
   at <Root>.wp-blog-header_php.<Main>(Pchp.Core.Context, Pchp.Core.PhpArray, System.Object, System.RuntimeTypeHandle)
   at <Root>.index_php.<Main>(Pchp.Core.Context, Pchp.Core.PhpArray, System.Object, System.RuntimeTypeHandle)
   at <Root>.index_php.<Main>`0(Pchp.Core.Context, Pchp.Core.PhpArray, System.Object, System.RuntimeTypeHandle)
   at Peachpie.AspNetCore.Web.RequestContextCore.ProcessScript(ScriptInfo)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware.InvokeAndDispose(Peachpie.AspNetCore.Web.RequestContextCore, ScriptInfo)
   at Peachpie.AspNetCore.Web.PhpHandlerMiddleware+<>c__DisplayClass13_0.<Invoke>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
```

**Additional context**
Installed plugins: WP SMTP, SyntaxHighlighter Evolved
Theme: Tusi

**Comment by jakubmisek** [comment]
Thanks for the issue and the stack trace.

When it happens again, can you please verify, the stack trace is the same?

**Comment by hez2010** [comment]
After upgrading to .NET 5 RC1, the issue seems gone.

**Comment by jakubmisek** [comment]
@hez2010 thank you, please let us know if there would be any more details in the future.
